[package]
name = "bike_blockchain_backend"
version = "0.1.0"
authors = ["Christoffer Gustafsson <christoffer.golf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
